version: "3.8"

services:
  todo:
    build:
      context: .
      dockerfile: Dockerfile
    image: rust-todo
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - common-network

networks:
  common-network:
    name: common-network
    driver: bridge
